POST http://localhost:8080/login 
Content-Type:  application/json
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QzQGdtYWlsLmNvbSIsImV4cCI6MTcyMTk5ODAwMCwidXNlcklkIjozfQ.f0CPBen-mVv4envr8Q4ywS4HYxGDskGNsPwm7HlAy4E

{
    "email": "test2@gmail.com",
    "password": "test"
}