PUT http://localhost:8080/events/4
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsImV4cCI6MTcyMTk5ODEwNywidXNlcklkIjoyfQ.TpaERFC8PZg6MRGRyo5VeKyabi973hRDtldKEqI6wZI

{
  "name": "Updated Test event",
  "description": "A test event",
  "location": "Updated test Location",
  "dateTime": "2025-01-01T15:30:00.000Z"
}